import Head from 'next/head'
import Hero from '../components/Hero'
import JudulProject from '../components/JudulProject'
import Navbar from '../components/Navbar'

const Home = () => {
  return (
    <>
    <div>
      <Head>
        <title>Art By Code</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <Navbar/>
      <Hero/>
      
    </div>

    
  </>
  )
}

// memakai headless ui dr tailwind (npm install @headlessui/react)

export default Home
